//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation::*;
use crate::MetricKit::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "MetricKit_MXCallStackTree")]
    /**
     @class         MXCallStackTree
    @abstract      A data class that encapsulates call stack trees vended by MetricKit.
    @discussion    You should use the JSONRepresentation API to generate human readable call stack trees for symbolication off device.
    */
    pub struct MXCallStackTree;

    #[cfg(feature = "MetricKit_MXCallStackTree")]
    unsafe impl ClassType for MXCallStackTree {
        type Super = NSObject;
    }
);

#[cfg(feature = "MetricKit_MXCallStackTree")]
/**
 @class         MXCallStackTree
@abstract      A data class that encapsulates call stack trees vended by MetricKit.
@discussion    You should use the JSONRepresentation API to generate human readable call stack trees for symbolication off device.
*/
unsafe impl NSCoding for MXCallStackTree {}

#[cfg(feature = "MetricKit_MXCallStackTree")]
/**
 @class         MXCallStackTree
@abstract      A data class that encapsulates call stack trees vended by MetricKit.
@discussion    You should use the JSONRepresentation API to generate human readable call stack trees for symbolication off device.
*/
unsafe impl NSObjectProtocol for MXCallStackTree {}

#[cfg(feature = "MetricKit_MXCallStackTree")]
/**
 @class         MXCallStackTree
@abstract      A data class that encapsulates call stack trees vended by MetricKit.
@discussion    You should use the JSONRepresentation API to generate human readable call stack trees for symbolication off device.
*/
unsafe impl NSSecureCoding for MXCallStackTree {}

extern_methods!(
    /**
     @class         MXCallStackTree
    @abstract      A data class that encapsulates call stack trees vended by MetricKit.
    @discussion    You should use the JSONRepresentation API to generate human readable call stack trees for symbolication off device.
    */
    #[cfg(feature = "MetricKit_MXCallStackTree")]
    unsafe impl MXCallStackTree {
        #[cfg(feature = "Foundation_NSData")]
        #[method_id(@__retain_semantics Other JSONRepresentation)]
        pub unsafe fn JSONRepresentation(&self) -> Id<NSData>;
    }
);
