//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::ClassKit::*;
use crate::Foundation::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "ClassKit_CLSActivityItem")]
    /**
     @abstract      CLSActivityItem is used to gather information about the activity generated by a user.
    */
    pub struct CLSActivityItem;

    #[cfg(feature = "ClassKit_CLSActivityItem")]
    unsafe impl ClassType for CLSActivityItem {
        #[inherits(NSObject)]
        type Super = CLSObject;
    }
);

#[cfg(feature = "ClassKit_CLSActivityItem")]
/**
 @abstract      CLSActivityItem is used to gather information about the activity generated by a user.
*/
unsafe impl NSCoding for CLSActivityItem {}

#[cfg(feature = "ClassKit_CLSActivityItem")]
/**
 @abstract      CLSActivityItem is used to gather information about the activity generated by a user.
*/
unsafe impl NSObjectProtocol for CLSActivityItem {}

#[cfg(feature = "ClassKit_CLSActivityItem")]
/**
 @abstract      CLSActivityItem is used to gather information about the activity generated by a user.
*/
unsafe impl NSSecureCoding for CLSActivityItem {}

extern_methods!(
    /**
     @abstract      CLSActivityItem is used to gather information about the activity generated by a user.
    */
    #[cfg(feature = "ClassKit_CLSActivityItem")]
    unsafe impl CLSActivityItem {
        #[cfg(feature = "Foundation_NSString")]
        /**
         @abstract      Title of what this ActivityItem respresents.
        @discussion    This will be the title associated with the activity item in the generated progress report.
        */
        #[method_id(@__retain_semantics Other title)]
        pub unsafe fn title(&self) -> Id<NSString>;

        #[cfg(feature = "Foundation_NSString")]
        /**
         @abstract      Title of what this ActivityItem respresents.
        @discussion    This will be the title associated with the activity item in the generated progress report.
        */
        #[method(setTitle:)]
        pub unsafe fn setTitle(&self, title: &NSString);

        #[cfg(feature = "Foundation_NSString")]
        /**
         @abstract      An identifier that is unique within its owning activity
        @discussion    The identifier can be used to look up existing activityItems in a given activity.
        */
        #[method_id(@__retain_semantics Other identifier)]
        pub unsafe fn identifier(&self) -> Id<NSString>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;
    }
);
