//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Contacts::*;
use crate::CoreLocation::*;
use crate::Foundation::*;
use crate::MapKit::*;

pub type MKMapSnapshotCompletionHandler = *mut Block<(*mut MKMapSnapshot, *mut NSError), ()>;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "MapKit_MKMapSnapshotter")]
    #[cfg(not(any(target_os = "watchos")))]
    pub struct MKMapSnapshotter;

    #[cfg(not(any(target_os = "watchos")))]
    #[cfg(feature = "MapKit_MKMapSnapshotter")]
    unsafe impl ClassType for MKMapSnapshotter {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "MapKit_MKMapSnapshotter")]
#[cfg(not(any(target_os = "watchos")))]
unsafe impl NSObjectProtocol for MKMapSnapshotter {}

#[cfg(not(any(target_os = "watchos")))]
extern_methods!(
    #[cfg(feature = "MapKit_MKMapSnapshotter")]
    #[cfg(not(any(target_os = "watchos")))]
    unsafe impl MKMapSnapshotter {
        #[cfg(feature = "MapKit_MKMapSnapshotOptions")]
        #[method_id(@__retain_semantics Init initWithOptions:)]
        pub unsafe fn initWithOptions(
            this: Option<Allocated<Self>>,
            options: &MKMapSnapshotOptions,
        ) -> Id<Self>;

        #[method(startWithCompletionHandler:)]
        pub unsafe fn startWithCompletionHandler(
            &self,
            completion_handler: MKMapSnapshotCompletionHandler,
        );

        #[method(cancel)]
        pub unsafe fn cancel(&self);

        #[method(isLoading)]
        pub unsafe fn isLoading(&self) -> bool;
    }
);

#[cfg(not(any(target_os = "watchos")))]
extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "MapKit_MKMapSnapshotter")]
    #[cfg(not(any(target_os = "watchos")))]
    unsafe impl MKMapSnapshotter {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
