//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
#![allow(unused_imports)]
#![allow(deprecated)]
#[path = "LABase.rs"]
mod __LABase;
#[path = "LAContext.rs"]
mod __LAContext;
#[path = "LAError.rs"]
mod __LAError;
#[path = "LAPersistedRight.rs"]
mod __LAPersistedRight;
#[path = "LAPrivateKey.rs"]
mod __LAPrivateKey;
#[path = "LAPublicDefines.rs"]
mod __LAPublicDefines;
#[path = "LAPublicKey.rs"]
mod __LAPublicKey;
#[path = "LARequirement.rs"]
mod __LARequirement;
#[path = "LARight.rs"]
mod __LARight;
#[path = "LARightStore.rs"]
mod __LARightStore;
#[path = "LASecret.rs"]
mod __LASecret;

pub use self::__LAContext::LAAccessControlOperation;
pub use self::__LAContext::LAAccessControlOperationCreateItem;
pub use self::__LAContext::LAAccessControlOperationCreateKey;
pub use self::__LAContext::LAAccessControlOperationUseItem;
pub use self::__LAContext::LAAccessControlOperationUseKeyDecrypt;
pub use self::__LAContext::LAAccessControlOperationUseKeyKeyExchange;
pub use self::__LAContext::LAAccessControlOperationUseKeySign;
pub use self::__LAContext::LABiometryNone;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAContext::LABiometryType;
pub use self::__LAContext::LABiometryTypeFaceID;
pub use self::__LAContext::LABiometryTypeNone;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAContext::LABiometryTypeTouchID;
#[cfg(feature = "LocalAuthentication_LAContext")]
pub use self::__LAContext::LAContext;
pub use self::__LAContext::LAPolicy;
pub use self::__LAContext::LAPolicyDeviceOwnerAuthentication;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAContext::LAPolicyDeviceOwnerAuthenticationWithBiometrics;
#[cfg(not(any(target_os = "ios", target_os = "watchos")))]
pub use self::__LAContext::LAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch;
#[cfg(not(any(target_os = "ios", target_os = "watchos")))]
pub use self::__LAContext::LAPolicyDeviceOwnerAuthenticationWithWatch;
#[cfg(not(any(target_os = "ios", target_os = "macos")))]
pub use self::__LAContext::LAPolicyDeviceOwnerAuthenticationWithWristDetection;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAContext::LATouchIDAuthenticationMaximumAllowableReuseDuration;
pub use self::__LAError::LAErrorDomain;
#[cfg(feature = "LocalAuthentication_LAPersistedRight")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAPersistedRight::LAPersistedRight;
#[cfg(feature = "LocalAuthentication_LAPrivateKey")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAPrivateKey::LAPrivateKey;
#[cfg(feature = "LocalAuthentication_LAPublicKey")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LAPublicKey::LAPublicKey;
#[cfg(feature = "LocalAuthentication_LAAuthenticationRequirement")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARequirement::LAAuthenticationRequirement;
#[cfg(feature = "LocalAuthentication_LABiometryFallbackRequirement")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARequirement::LABiometryFallbackRequirement;
#[cfg(feature = "LocalAuthentication_LARight")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARight::LARight;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARight::LARightState;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARight::LARightStateAuthorized;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARight::LARightStateAuthorizing;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARight::LARightStateNotAuthorized;
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARight::LARightStateUnknown;
#[cfg(feature = "LocalAuthentication_LARightStore")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LARightStore::LARightStore;
#[cfg(feature = "LocalAuthentication_LASecret")]
#[cfg(not(any(target_os = "watchos")))]
pub use self::__LASecret::LASecret;
