//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AuthenticationServices::*;
use crate::Foundation::*;

#[cfg(not(any(target_os = "tvos", target_os = "watchos")))]
extern_protocol!(
    pub unsafe trait ASAuthorizationPublicKeyCredentialAssertion:
        ASPublicKeyCredential
    {
        #[cfg(feature = "Foundation_NSData")]
        #[cfg(not(any(target_os = "tvos", target_os = "watchos")))]
        #[method_id(@__retain_semantics Other rawAuthenticatorData)]
        unsafe fn rawAuthenticatorData(&self) -> Id<NSData>;

        #[cfg(feature = "Foundation_NSData")]
        #[cfg(not(any(target_os = "tvos", target_os = "watchos")))]
        #[method_id(@__retain_semantics Other userID)]
        unsafe fn userID(&self) -> Id<NSData>;

        #[cfg(feature = "Foundation_NSData")]
        #[cfg(not(any(target_os = "tvos", target_os = "watchos")))]
        #[method_id(@__retain_semantics Other signature)]
        unsafe fn signature(&self) -> Id<NSData>;
    }

    unsafe impl ProtocolType for dyn ASAuthorizationPublicKeyCredentialAssertion {}
);
